steps:
  - uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - uses: ruby/setup-ruby@v1
    with:
      ruby-version: "3.2"
      bundler-cache: true
      working-directory: site

  - name: Install Python dependencies
    run: pip install -r scripts/requirements.txt

  - name: Install Node.js
    uses: actions/setup-node@v4
    with:
      node-version: "20"
