#!/usr/bin/env python3
"""Generate the landing page "Recent Resources" list from git history.

The home page shows recently *added* documents. Rather than relying on a
manually maintained `pub_date`, this script derives each resource's
date-added from git (the first commit that introduced the resource's
Markdown file, falling back to its `local_path` source file). Files not yet
committed are treated as added "now" so freshly added resources surface at
the top. The result is written as an ordered Jekyll data file consumed by
`_layouts/home.html`, so the list refreshes on every build.

Archived (superseded) resources are excluded.

Usage:
    python scripts/build_recent.py
"""

import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

_FM_RE = re.compile(r"^---\s*\n(.*?\n)---\s*\n", re.DOTALL)


def _parse_front_matter(text: str) -> dict:
    m = _FM_RE.match(text)
    if not m:
        return {}
    return yaml.safe_load(m.group(1)) or {}


def _git_added_date(repo_root: Path, rel_path: str) -> str | None:
    """Return the ISO date of the commit that first added `rel_path`, or None."""
    try:
        out = subprocess.run(
            ["git", "log", "--diff-filter=A", "--follow",
             "--format=%aI", "-1", "--", rel_path],
            cwd=repo_root, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return out or None


def _resource_url(md_file: Path, resources_dir: Path) -> str:
    """Match Jekyll's `/resources/:path/` permalink (baseurl applied in template)."""
    rel = md_file.relative_to(resources_dir).with_suffix("")
    return f"/resources/{rel.as_posix()}/"


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    resources_dir = repo_root / "site" / "_resources"
    data_file = repo_root / "site" / "_data" / "recent_resources.yml"

    if not resources_dir.is_dir():
        print(f"ERROR: resources directory not found: {resources_dir}", file=sys.stderr)
        return 1

    now_iso = datetime.now(timezone.utc).isoformat()
    entries = []

    for md_file in sorted(resources_dir.rglob("*.md")):
        fm = _parse_front_matter(md_file.read_text(encoding="utf-8"))
        if not fm or fm.get("archived") is True:
            continue

        rel_md = md_file.relative_to(repo_root).as_posix()
        added = _git_added_date(repo_root, rel_md)
        if not added:
            local_path = fm.get("local_path")
            if local_path:
                added = _git_added_date(repo_root, str(local_path))
        if not added:
            # Uncommitted / newly added resource: treat as most recent.
            added = now_iso

        categories = fm.get("categories")
        if not categories and fm.get("category"):
            categories = [fm["category"]]

        entries.append({
            "title": str(fm.get("title", md_file.stem)),
            "url": _resource_url(md_file, resources_dir),
            "summary": str(fm.get("summary", "")).strip(),
            "categories": categories or [],
            "date_added": added,
        })

    entries.sort(key=lambda e: e["date_added"], reverse=True)

    header = ("# Generated by scripts/build_recent.py - do not edit by hand.\n"
              "# Ordered list of non-archived resources, most recently added first.\n")
    data_file.parent.mkdir(parents=True, exist_ok=True)
    data_file.write_text(
        header + yaml.safe_dump(entries, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )

    print(f"Wrote {len(entries)} entries to {data_file.relative_to(repo_root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
